# Change these first
owner: HighTide # Your GitHub organization or username, where this repository lives
repo: status.hightide.dev # The name of this repository

sites:
  - name: hightide.dev
    url: https://hightide.dev
  - name: koetse.eu
    url: https://koetse.eu
  - name: home.koetse.eu
    url: https://home.koetse.eu
  - name: koetse.nl
    url: https://koetse.nl
  - name: hyves.nl
    url: https://hyves.nl
  - name: DatumKiezen.nl
    url: https://DatumKiezen.nl    
  - name: DatumKiezer.nl
    url: https://DatumKiezer.nl        

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hightide.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Hightide Status :)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
